runtime: python39

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

entrypoint: python index.py

handlers:
- url: /.*
  script: auto
  secure: always
